2024-10-03 12:05:39,748 INFO    MainThread:3537076 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-10-03 12:05:39,748 INFO    MainThread:3537076 [wandb_setup.py:_flush():76] Configure stats pid to 3537076
2024-10-03 12:05:39,748 INFO    MainThread:3537076 [wandb_setup.py:_flush():76] Loading settings from /home/howon/.config/wandb/settings
2024-10-03 12:05:39,748 INFO    MainThread:3537076 [wandb_setup.py:_flush():76] Loading settings from /home/howon/aistats25-exp/wandb/settings
2024-10-03 12:05:39,749 INFO    MainThread:3537076 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-10-03 12:05:39,749 INFO    MainThread:3537076 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-10-03 12:05:39,749 INFO    MainThread:3537076 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'nn_exp.py', 'program_abspath': '/home/howon/aistats25-exp/nn_exp.py', 'program': '/home/howon/aistats25-exp/nn_exp.py'}
2024-10-03 12:05:39,750 INFO    MainThread:3537076 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-10-03 12:05:39,750 INFO    MainThread:3537076 [wandb_init.py:_log_setup():520] Logging user logs to /home/howon/aistats25-exp/wandb/run-20241003_120539-jap02bgo/logs/debug.log
2024-10-03 12:05:39,750 INFO    MainThread:3537076 [wandb_init.py:_log_setup():521] Logging internal logs to /home/howon/aistats25-exp/wandb/run-20241003_120539-jap02bgo/logs/debug-internal.log
2024-10-03 12:05:39,750 INFO    MainThread:3537076 [wandb_init.py:init():560] calling init triggers
2024-10-03 12:05:39,751 INFO    MainThread:3537076 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-10-03 12:05:39,751 INFO    MainThread:3537076 [wandb_init.py:init():610] starting backend
2024-10-03 12:05:39,751 INFO    MainThread:3537076 [wandb_init.py:init():614] setting up manager
2024-10-03 12:05:39,756 INFO    MainThread:3537076 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-03 12:05:39,758 INFO    MainThread:3537076 [wandb_init.py:init():622] backend started and connected
2024-10-03 12:05:39,767 INFO    MainThread:3537076 [wandb_init.py:init():711] updated telemetry
2024-10-03 12:05:39,768 INFO    MainThread:3537076 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-10-03 12:05:39,991 INFO    MainThread:3537076 [wandb_run.py:_on_init():2396] communicating current version
2024-10-03 12:05:40,068 INFO    MainThread:3537076 [wandb_run.py:_on_init():2405] got version response upgrade_message: "wandb version 0.18.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-10-03 12:05:40,068 INFO    MainThread:3537076 [wandb_init.py:init():795] starting run threads in backend
2024-10-03 12:05:42,652 WARNING MainThread:3537076 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/home/howon/.conda/envs/cs552/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/howon/.conda/envs/cs552/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/howon/.conda/envs/cs552/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/howon/.conda/envs/cs552/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/howon/.conda/envs/cs552/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/howon/.conda/envs/cs552/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/howon/.conda/envs/cs552/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-10-03 12:05:47,955 WARNING MsgRouterThr:3537076 [router.py:message_loop():77] message_loop has been closed
